/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Challenge2026RouteImport } from './routes/challenge2026'
import { Route as IndexRouteImport } from './routes/index'

const Challenge2026Route = Challenge2026RouteImport.update({
  id: '/challenge2026',
  path: '/challenge2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge2026': typeof Challenge2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge2026': typeof Challenge2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge2026': typeof Challenge2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/challenge2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/challenge2026'
  id: '__root__' | '/' | '/challenge2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Challenge2026Route: typeof Challenge2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/challenge2026': {
      id: '/challenge2026'
      path: '/challenge2026'
      fullPath: '/challenge2026'
      preLoaderRoute: typeof Challenge2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Challenge2026Route: Challenge2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
